// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: '1:958088539228:web:7e279cfd7eeeca269e4a99',
    messagingSenderId: '958088539228',
    projectId: 'marketplace-52d40',
    authDomain: 'marketplace-52d40.firebaseapp.com',
    storageBucket: 'marketplace-52d40.appspot.com',
    measurementId: 'G-4S086B8W2W',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!, 
    appId: '1:958088539228:android:174ddb4c8794590f9e4a99',
    messagingSenderId: '958088539228',
    projectId: 'marketplace-52d40',
    storageBucket: 'marketplace-52d40.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:958088539228:ios:ed77f3eb5d5b304d9e4a99',
    messagingSenderId: '958088539228',
    projectId: 'marketplace-52d40',
    storageBucket: 'marketplace-52d40.appspot.com',
    iosClientId:
        '958088539228-bjh0m61apl5d6k8tkilvh14t57ri6eki.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey:  dotenv.env['FIREBASE_MACOS_API_KEY']!,
    appId: '1:958088539228:ios:5a04caa79f357d429e4a99',
    messagingSenderId: '958088539228',
    projectId: 'marketplace-52d40',
    storageBucket: 'marketplace-52d40.appspot.com',
    iosClientId:
        '958088539228-vn7rsmcv0l1la8kltib4deaq82pv3o69.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
